/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLogRouteImport } from './routes/app.log'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AdminViolationsRouteImport } from './routes/admin.violations'
import { Route as AdminVerifiedRouteImport } from './routes/admin.verified'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminClearanceRouteImport } from './routes/admin.clearance'
import { Route as AdminReviewIdRouteImport } from './routes/admin.review.$id'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AdminViolationsRoute = AdminViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerifiedRoute = AdminVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClearanceRoute = AdminClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewIdRoute = AdminReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/log': typeof AppLogRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/log': typeof AppLogRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/system': typeof SystemRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/verified': typeof AdminVerifiedRoute
  '/admin/violations': typeof AdminViolationsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/log': typeof AppLogRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/system'
    | '/admin/clearance'
    | '/admin/opportunities'
    | '/admin/profile'
    | '/admin/queue'
    | '/admin/students'
    | '/admin/verified'
    | '/admin/violations'
    | '/app/history'
    | '/app/home'
    | '/app/log'
    | '/app/profile'
    | '/app/reports'
    | '/admin/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/system'
    | '/admin/clearance'
    | '/admin/opportunities'
    | '/admin/profile'
    | '/admin/queue'
    | '/admin/students'
    | '/admin/verified'
    | '/admin/violations'
    | '/app/history'
    | '/app/home'
    | '/app/log'
    | '/app/profile'
    | '/app/reports'
    | '/admin/review/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/system'
    | '/admin/clearance'
    | '/admin/opportunities'
    | '/admin/profile'
    | '/admin/queue'
    | '/admin/students'
    | '/admin/verified'
    | '/admin/violations'
    | '/app/history'
    | '/app/home'
    | '/app/log'
    | '/app/profile'
    | '/app/reports'
    | '/admin/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log': {
      id: '/app/log'
      path: '/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/violations': {
      id: '/admin/violations'
      path: '/violations'
      fullPath: '/admin/violations'
      preLoaderRoute: typeof AdminViolationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verified': {
      id: '/admin/verified'
      path: '/verified'
      fullPath: '/admin/verified'
      preLoaderRoute: typeof AdminVerifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clearance': {
      id: '/admin/clearance'
      path: '/clearance'
      fullPath: '/admin/clearance'
      preLoaderRoute: typeof AdminClearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review/$id': {
      id: '/admin/review/$id'
      path: '/review/$id'
      fullPath: '/admin/review/$id'
      preLoaderRoute: typeof AdminReviewIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClearanceRoute: typeof AdminClearanceRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminVerifiedRoute: typeof AdminVerifiedRoute
  AdminViolationsRoute: typeof AdminViolationsRoute
  AdminReviewIdRoute: typeof AdminReviewIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClearanceRoute: AdminClearanceRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminVerifiedRoute: AdminVerifiedRoute,
  AdminViolationsRoute: AdminViolationsRoute,
  AdminReviewIdRoute: AdminReviewIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLogRoute: typeof AppLogRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppLogRoute: AppLogRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
